#!/usr/bin/env python
# -*- coding: utf-8 -*-

######################################## importing relevant Python packages ##
from pcraster import *                                                      
from pcraster.framework import *
from subprocess import *
import numpy as np
import os
import shutil
import sys

##################################################### Specifying file paths ##

# !!!!! THESE NEED TO BE CHANGEd ACCORDING TO YOUR SYSTEM  !!!!!  
sys.path.append( "C:\Users\simon\OneDrive\Documents\JHU\SAS\IsoSNOW\ToRG" ) # adding path that holds model configuration files and input files specified below
import IsoSnow_initialPara_2017_07_04                                     # a script to specify parameter values and initial conditions
import IsoSnow_reporting_2017_07_04                                       # a script to specify what model output to save to disk
import IsoSnow_model_2016_12_22_PA                                        # specify what module versions are used #!!!# important to update when changes to these are made #!!!# 
wd  ='C:\Users\simon\OneDrive\Documents\JHU\SAS\IsoSNOW\ToRG'     # set working directory to where this script is stored
os.chdir(wd)

# remove model output folders to allow new model run 
dirs = os.walk('.').next()[1]                                                 # find all directories
numdirs = [x for x in dirs if x.isdigit()]                                   # find directories which are numbers (where prior model output lies) 
for y in numdirs:                                                            # remove these directories
    shutil.rmtree(wd+"/"+y)
    

class IsoModel(DynamicModel, MonteCarloModel):                              # model syntax in the PCraster dynamic model. 
  def __init__(self, number_of_timesteps,location_of_input_folder, number_of_samples):
    DynamicModel.__init__(self)
    MonteCarloModel.__init__(self)                                            # The model code operates in MC mode. To run MC further specification on parameter ranges etc required.
                                                                              # MC sampling not used in this deterministic example 
    #input variables to the actual model call
    self.number_of_timesteps = number_of_timesteps                            # values for these given at the very end, variables need to be defined here
    self.input_folder        = location_of_input_folder
    self.number_of_samples   = number_of_samples  
    setclone(self.input_folder+"/maps/mask_new.map")                          # clone map that specifies the dimensions of the model domain
                                             
    
  def initial(self):
      
    ################################################## MODEL INITIALISATION ## 

    # Here you switch on/off reporting         #
                                               #    
    # WRITE MAP OUTPUT          ????           #
    self.reportSpatial        = False          #
                                               #
    # WRITE TIMESERIES OUTPUT   ????           #
    self.reportTimeseries     = True           #
                                               #
    # CALCULATE WATER AGES      ????           #
    self.doAges               = True           #


    # specify model parameters and initial conditions in the script 
    IsoSnow_initialPara_2017_07_04.iniParameters(self)
    
  ####################################################### RUNNING THE MODEL ##

    
  def dynamic(self):
    print 'timestep', self.currentTimeStep(), 'in sample number',self.currentSampleNumber()
    self.setQuiet(quiet=True)

    
    # specify meteorological model input
    T = timeinputscalar(self.input_folder+"/MET_data/AirTemp.tss",1)          # Air temperature [C]
    T += self.Tgrad * self.altDiff                                            # correct for temperature lapse
    P = timeinputscalar(self.input_folder+"/MET_data/Precip_0.tss",1)          # precip timeseries, given 0 timeseries as input in this example
    self.radRs      = self.readDeterministic(self.input_folder+"/output_Rs/RsCorr") # spatially distributed global radiation (MJ/d*m2) generated by separately. Also spatially uniform radiation can be used.
    self.WSin       = timeinputscalar(self.input_folder+"/MET_data/WindSpeed.tss",1) # windspeed timeseries, spatially uniform
    self.RH         = timeinputscalar(self.input_folder+"/MET_data/RelHum.tss",1) # relative humidity timeseries, spatially unifrom 
        
    Pconc= timeinputscalar(self.input_folder+"/PconcO18.tss", 1)              # timeseries of precipitation isotope concentration, here 0 because precip not considered  
    
    #################################################### EXECUTE SNOW MODEL ##
    IsoSnow_model_2016_12_22_PA.update(self, P, T, Pconc)
    
    #################################### SPECIFY VARIABLES TO WRITE TO DISK ##
    IsoSnow_reporting_2017_07_04.reportAll(self)


# GIVE MODEL INPUT PARAMETERS
number_of_timesteps =   212                     
location_of_input_folder = "Input"
number_of_samples = 1  

myModel = IsoModel(number_of_timesteps, location_of_input_folder,number_of_samples)
dynamicModel = DynamicFramework(myModel, lastTimeStep=number_of_timesteps, firstTimestep=1)
mcModel = MonteCarloFramework(dynamicModel, nrSamples=number_of_samples)
mcModel.run()

print('RUN COMPLETED')
print "for model output check:" ,wd,"\\1" 